package org.save.model.enums.tatum;

public enum TransactionType {
  FAILED,
  DEBIT_PAYMENT,
  CREDIT_PAYMENT,
  CREDIT_DEPOSIT,
  DEBIT_WITHDRAWAL,
  CANCEL_WITHDRAWAL,
  DEBIT_OUTGOING_PAYMENT,
  CREDIT_INCOMING_PAYMENT,
  EXCHANGE_BUY,
  EXCHANGE_SELL
}
