insert into public.play_list (id, title, description)
values  (9, 'Cheap SP500 stocks', 'The cheapest stocks in the best known index – SP500'),
        (10, 'Post IPO', 'Companies just after public offering or listing on national exchanges such as NYSE and NASDAQ'),
        (11, 'Dowjones stocks', 'Index, consisting of biggest 30 companies in the US'),
        (12, 'Online education', 'Companies, helping you to gain knowledge and study online'),
        (13, 'Companies that blocked Trump', 'Companies where accounts of Trump were banned'),
        (14, 'Telecommunication', 'Companies involved in electronic transmission of information over distances, like voice telephone calls, data, text, images, or video, etc.'),
        (15, 'Consumer cyclical with high earnings grow', 'Income or earnings growth rate of these consumer cyclical companies is the highest one in the whole sector'),
        (16, 'Discount retailers', 'These companies sell more goods at lower prices, because they believe that low prices are their competitive advantage'),
        (17, 'Most growing consumer defensive companies', 'Consumer defensive companies with the highest revenue growth rate in the sector'),
        (18, 'Consumer defensive with high earnings growth', 'Income or earnings growth rate of these consumer defensive companies is the highest one in the whole sector'),
        (19, 'Masayoshi Son''s portfolio', 'Masayoshi Son is a Japanese billionaire, famous for being one of the best investors in the world'),
        (20, 'Cannabis', 'Companies involved in legal cultivation and producing of marijuana'),
        (21, 'WFH essentials', 'These compnaies are focused on remote work, providing solutions to accomplish it'),
        (22, 'Most growing real estate companies', 'Real estate companies with the highest revenue growth rate in the sector'),
        (23, 'Diagnosis and research', 'They involved in the process of determining which disease, condition or symptoms a person has and in the subsequent research of them'),
        (25, 'Super bowl commercials', 'The most watched event in the US, famous also for its ads'),
        (26, 'Most growing basic materials', 'Basic materials companies with the highest revenue growth rate in the sector'),
        (27, 'Oil and gas with dividends', 'These companies have one of the highest dividend yield in the whole market'),
        (28, 'Basic materials most owned by institutions', 'These basic materials companies are favorites among hedge funds, banks, pension and mutual funds etc.'),
        (29, 'Restaurants', 'Chains of restaurants and stores with hundreds and thousands of locations'),
        (30, 'Biggest technology companies', 'Technology companies with biggest market capitalization'),
        (31, 'Technology most owned by institutions', 'These technology companies are favorites among hedge funds, banks, pension and mutual funds etc.'),
        (32, 'Elon''s twitter', 'Here are assets mentioned in twitter of Elon Musk'),
        (33, 'Healthcare most owned by institutions', 'These healthcare companies are favorites among hedge funds, banks, pension and mutual funds etc.'),
        (34, 'Biggest entertainment companies', 'Companies with biggest market capitalization in the entertainment industry'),
        (35, 'Biggest communication services', 'Communication services companies with biggest market capitalization'),
        (36, 'Internet retail', 'E-commerce companies involved in the business of electronically buying or selling of products and goods on online services or over the Internet'),
        (37, 'Biggest consumer cyclical', 'Consumer cyclical companies with biggest market capitalization'),
        (38, 'Most growing energy companies', 'Energy companies with the highest revenue growth rate in the sector'),
        (39, 'Biggest energy companies', 'Energy companies with biggest market capitalization in the sector'),
        (40, 'Energy most owned by institutions', 'These energy companies are favorites among hedge funds, banks, pension and mutual funds etc.'),
        (41, 'Biggest financial companies', 'Financial companies with biggest market capitalization in the sector'),
        (42, 'Aerospace and defense', 'Companies involved in both aviation and space flights'),
        (43, 'Most growing industrial stocks', 'Industrial companies with the highest revenue growth rate in the sector'),
        (44, 'Industrials with dividends', 'Industrial companies with the highest dividend yield in the sector'),
        (45, 'Industrial most owned by institutions', 'These industrial companies are favorites among hedge funds, banks, pension and mutual funds etc.'),
        (46, 'Companies with LGBTQ management', 'Companies where senior executives are LGBTQ people'),
        (47, 'Christmas stocks', 'Companies directly associated with the Christmas'),
        (48, 'Utilities', 'Companies that provide basic amenities, such as water, sewage services, electricity, dams and natural gas'),
        (49, 'Blockchain', 'Blockchain is a digital record of transactions, making it difficult or impossible to change, hack, or cheat the system'),
        (50, 'VR and AR', 'Simulated or interactive experience that can be similar or completely different from the real world'),
        (51, 'Chip makers and semiconductors', 'Essential components of any electronic device in communications, computing, healthcare, military systems, transportation, clean energy etc.'),
        (52, 'Social medias', 'Companies helping us to create, watch, read and share content or to communicate with others'),
        (53, 'Most growing technology companies', 'Technology companies with the highest revenue growth rate in the sector'),
        (54, 'High growing SP500 stocks', 'Companies with the highest revenue growth rate in the best-known index–SP500'),
        (4, 'Cheap and growing technology companies     ', 'Technology companies with high revenue growth rate, while the stock price is low, relativeliy to it’s peers'),
        (55, 'Genomics', 'Companiesfocused on identifying disease-causing genes and new therapeutic strategies based on this data or gene editing'),
        (56, 'Communication services most owned by institutions', 'These communication services companies are favorites among hedge funds, banks, pension and mutual funds etc.'),
        (57, 'Most growing communication services', 'Communication services companies with the highest revenue growth rate in the sector'),
        (58, 'Most growing consumer cyclical', 'Consumer cyclical companies with the highest revenue growth rate in the sector'),
        (59, 'Asset management', 'Companies involved in investing assets or moeny on behalf of their clients, both indivtuals and enterprises'),
        (60, 'Cheap and growing consumer cyclical', 'Consumer cyclical companies with high revenue growth rate, while the stock price is low relatively to it’s peers'),
        (61, 'Foreign most growing companies', 'Non US companies with the highest revenue growth rate'),
        (62, 'Future of transport', 'Autonomous vehicles, e-vehicles, space tourism companies are here'),
        (63, 'Fintech', 'Companies using technology and innovations to improve activities in finance or to deliver financial services'),
        (64, 'Beauty', 'These companies provide products, making people look their best (cosmetics, personal care, etc.)'),
        (65, 'Technology most recommended by analysts', 'Most recommended companies to invest in, based on research from wall street banks and institutions'),
        (66, 'George Soros'' portfolio', 'He is an American billionaire investor and philanthropist, famous for a single-day gain of $1 billion led by collapse of the British pound'),
        (67, 'Fight with COVID-19', 'Companies involved in fight with COVID-19, which changed and still is shaping our everyday life'),
        (68, 'AI', 'Artificial intelligence (AI) is the ability of a computer or program to do tasks usually done by humans'),
        (69, 'Internet of things', 'The interconnection via the internet of computing devices “things”, enabling them to send, exchange and receive data.'),
        (70, 'Food delivery', 'With them you can order food from restaurants, groceries, cafes etc.'),
        (71, 'Telehealth and telemedicine', 'Companies providing health-related services and information via internet, apps, devices and telecommunication technologies.'),
        (72, 'Cheap and growing healthcare companies', 'Healthcare companies with high revenue growth rate, while the stock price is low relatively to it’s peers'),
        (73, 'Most recommended healthcare stocks', 'Most recommended healthcare companies to invest in, based on research from wall street banks and institutions'),
        (75, 'Gold miners', 'Companies focused on mining of physical and virtual gold'),
        (76, 'Cheap and growing basic materials', 'Basic materials companies with high revenue growth rate, while the stock price is low relatively to it’s peers'),
        (77, 'Basic materials with high dividends', 'Basic materials companies with the highest dividends yield in the sector'),
        (78, 'Cheap and growing communication services', 'Communication services companies with high revenue growth rate, while the stock price is low relatively to it’s peers'),
        (79, 'Communication services with high dividends', 'Communication services companies with the highest dividend yield in the sector'),
        (80, 'Most recommended communication services', 'Most recommended communication services companies to invest in, based on research from wall street banks and institutions'),
        (81, 'Consumer cyclical with high dividends', 'Consumer cyclical companies with the highest dividend yield in the sector'),
        (82, 'Consumer cyclical most owned by institutions', 'These consumer cyclical companies are favorites among hedge funds, banks, pension and mutual funds etc.'),
        (83, 'Rule of forty', 'Software companies grouped on the principle that growth rate and profit margin'),
        (84, 'Transportation', 'Companies involved in moving people or freight from one location to another'),
        (85, 'Biggest healthcare companies', 'Healthcare companies with biggest market capitalization'),
        (86, 'Real estate companies with high dividends', 'Real estate companies with the highest dividend yield in the sector'),
        (87, 'Environment friendly', 'Not harmful to the environment companies, using green technologies or recycling materials'),
        (88, 'Healthcare with high earnings growth', 'Income or earnings growth rate of these healthcare companies is the highest one in the whole sector'),
        (89, 'Most recommended basic materials', 'Most recommended healthcare companies to invest in, based on research from wall street banks and institutions'),
        (90, 'Basic materials with high earnings grow', 'Incomeor earnings growth rate of these basic materials companies is the highest one in the whole sector'),
        (92, 'Most held by hedge funds', 'Companies held in most of hedge funds portfolios'),
        (93, '5 days after the earnings', 'Companies which released their quarterly or annual financial statements in last 5 days'),
        (94, 'Banks and capital markets', 'Companies that accept deposits from the public, hold money, invest or lend them to others'),
        (95, 'Logistics', 'The management of the flow of things from one place to another'),
        (96, 'Technology with high dividends', 'Income or earnings growth rate of these technology companies is the highest one in the whole sector'),
        (97, 'Best corporate culture', 'Company culture, refers to a set of beliefs and values that guide how decisions, hires, fires are made'),
        (98, 'Beverages', 'Companies producing nonalcoholic and alcoholic drinks'),
        (99, 'Consumer defensive with dividends', 'Consumer defensive companies with the highest dividend yield in the sector'),
        (100, 'Consumer defensive most owned by institutions', 'These consumer defensive companies are favorites among hedge funds, banks, pension and mutual funds etc.'),
        (101, 'Most recommended consumer defensive', 'Most recommended to invest in consumer defensive companies, based on research from wall street banks and institutions'),
        (102, 'Cheap and growing energy stocks', 'Energy companies with high revenue growth rate, while the stock price is relatively low to their peers'),
        (103, 'Most recommended energy stocks', 'Most recommended to invest in energy companies, based on research from wall street banks and institutions'),
        (104, 'Cheap and growing industrials', 'Industrial companies with high revenue growth rate, while the stock price is relatively low to their peers'),
        (105, 'Biggest industrial stocks', 'Industrial companies with biggest market capitalization in the sector'),
        (91, 'Woman led       ', 'Companies where senior executives are women'),
        (106, 'Renewable energy', 'Renewable energy is any energy that comes from renewable, natural sources, which can’t run out, such as sunlight, water, air and heat'),
        (107, 'Sharing economy', 'It is an economic system built around the sharing of resources, when individuals are able to borrow or rent assets owned by someone else'),
        (108, 'Insurance', 'Companies providing protection against a possible eventuality'),
        (109, 'Bill Gates'' portfolio', 'Bill Gates is a co-founder of Microsoft Corporation and one of the closest friends to Warren Buffet, who tought him how to invest and manage his fortune'),
        (110, 'Cloud, cloud and cloud', 'Companies providing different services through the Internet, including data storage, servers, databases, networking, and software'),
        (111, 'Cybersecurity', 'Companies producing technologies designed to protect networks, devices, programs, and data from attack, damage, or unauthorized access'),
        (112, 'Cheap and growing consumer defensive', 'Consumer defensive companies with high revenue growth rate, while the stock price is low relatively to it’s peers'),
        (113, 'Personal products', 'These companies are focused on personal hygiene, beautification and cleansing products, applied to any part of the human body'),
        (114, 'Energy companies with high earnings growth', 'Income or earnings growth rate of these energy companies is the highest one in the whole sector'),
        (115, 'Michael Burry''s portfolio', 'He is an American investor and hedge fund manager, famous for being the first investor to foresee and profit from the 2008 crisis'),
        (116, 'Industrials with high earnings growth', 'Income or earnings growth rate of these industrial companies is the highest one in the whole sector'),
        (117, 'Real estate companies most owned by institutions', 'These real estate companies are favorites among hedge funds, banks, pension and mutual funds etc.'),
        (118, 'Gaming', 'If you are a fan of video games or streams, this playlist is for you'),
        (119, 'Stay healthy', 'Companies providing products or services, improvong the quality of our lives'),
        (120, 'Drug manufacturing', 'Companies involved in the industrial-scale synthesis of pharmaceutical drugs or in drug production'),
        (121, 'Residential real estate', 'Companies, which are involved in a business with property used for residential purposes'),
        (122, 'Biotechnology', 'Companies using living systems and organisms to develop or make bio-based products such as antibiotics, hormones, etc.'),
        (123, 'Buffet''s portfolio', 'The investing icon and legend, Warren Buffett, who is considered as one of the most successful investors in the world'),
        (124, 'Dividends with future', 'Companies that both pay high dividends and  didn’t stop to grow and develop'),
        (125, 'Travelling', 'This list includes companies involved in the hospitality, transportation or in providing products and services to make a travel possible'),
        (126, 'Peter Thiel''s portfolio', 'One of best-known venture capitalist, who was the first investor in Facebook, and he is also co-founder of PayPal and Palantir Technologies'),
        (127, 'Bill Ackman''s portfolio', 'He is American billionaire investor and hedge fund manager, famous for his views, often appearances in the media and war with Herbalife'),
        (128, 'Jim Simmons'' portfolio', 'He is an American mathematician and billionaire hedge fund manage, famous for using mathematical models and algorithms to make investments'),
        (129, 'Technology with high earnings grow', 'Income or earnings growth rate of these technology companies is the highest one in the whole sector'),
        (130, 'Most recommended consumer cyclical by analysts', 'Most recommended consumer cyclical companies to invest in, based on research from wall street banks and institutions'),
        (132, 'Charlie Munger''s portfolio', 'He is the partner and the closest friend of Warren Buffet, famous for his tendency to simplify everything'),
        (133, 'Cheap and growing financial companies', 'Financial companies with high revenue growth rate, while the stock price is relatively low to their peers'),
        (134, 'Financial companies with dividends', 'Financial companies with the highest dividend yield in the sector'),
        (135, 'Most recommended financial companies', 'Most recommended to invest in financial companies, based on research from wall street banks and institutions'),
        (136, 'Companies with black management', 'Companies where senior executives are black'),
        (137, 'With strongest management team', 'Companies who have created the A  management team, capable to disrupt the industry'),
        (138, 'Cheap and growing real estate companies', 'Real estate companies with high revenue growth rate, while the stock price is relatively low to their peers'),
        (139, 'Real estate companies with high earnings growth', 'Income or earnings growth rate of these real estate companies is the highest one in the whole sector'),
        (140, 'Trending assets', 'In the last weeks these tickers are in the big demand'),
        (141, 'Financial with high earnings growths', 'Income or earnings growth rate of these financial companies is the highest one in the whole sector'),
        (142, 'Manufacturing', 'Companies involved in production of goods on a large scale using through the use of labor, machines, tools, and chemical or biological processing'),
        (143, 'Most popular stocks', 'The most popular companies ro invest in, which have dramatically changed our lives and continue to shape it right now'),
        (144, 'Medical devices and instruments', 'These companies are focused on devices, instruments and gadgets, providing diagnosis, treatment, helpping overcome diseases or improving quality of life'),
        (145, 'Most recommended real estate companies', 'Most recommended to invest in real estate companies, based on research from wall street banks and institutions'),
        (146, 'Communication services with high earnings grow', 'Income or earnings growth rate of these communication services companies is the highest one in the whole sector'),
        (147, 'Auto manufactures', 'These companies are involved in the design, developing, manufacturing, marketing, and selling of motor or electric vehicles'),
        (148, 'Most growing financial companies', 'Financial companies with the highest revenue growth rate in the sector'),
        (149, 'Financial companies most owned by intuitions', 'These financial companies are favorites among hedge funds, banks, pension and mutual funds etc.'),
        (131, '5G    ', 'The latest generation of cellular technology, engineered to increase the speed and responsiveness of the internet'),
        (24, 'New disrupters', 'Companies changing our lives in different fields and which started trading on national exchanges in last years'),
        (74, '5 days before the earnings', 'Companies which will release their quarterly or annual financial statements in next 5 days.'),
        (7, 'Biggest basic materials companies    ', 'Basic materials companies with biggest market capitalization'),
        (8, 'Most growing healthcare companies    ', 'Healthcare companies with the highest revenue growth rate in the sector'),
        (2, 'Healthcare with dividends    ', 'Healthcare companies with the highest dividends in the sector'),
        (1, 'Hardware producers    ', 'Companies producing physical elements or parts of computers, such as monitors, keyboards, CPUs, video cards etc.'),
        (3, 'Robotics    ', 'Companies involved in design, construction, and use of machines (robots) to perform tasks done traditionally by human beings'),
        (6, 'Vaccine producers    ', 'Companies involved in producing vaccines against COVID-19 or which are in the clinical trials'),
        (5, 'Airlines    ', 'Air transport services for traveling and freight');