insert into public.play_list_wrapper (id, category)
values  (1, 'Top'),
        (2, 'For you'),
        (3, 'Recommended'),
        (4, 'Technology'),
        (5, 'Healthcare'),
        (6, 'Portfolios'),
        (7, 'Communication services'),
        (8, 'Basic materials'),
        (9, 'Consumer cyclical'),
        (10, 'Finance'),
        (11, 'Management'),
        (12, 'Real estate'),
        (13, 'Others'),
        (14, 'Industrials');