insert into public.play_listc (id, category, imageurl, title)
values  (1, 'Top', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725084/New_movers.png', 'New disrupters'),
        (2, 'Top', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725104/Trending_assets.png', 'Trending assets'),
        (3, 'Top', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725107/Biggest_technology_companies.png', 'Biggest technology companies'),
        (5, 'For you', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725108/Internet_retail.png', 'Internet retail'),
        (6, 'For you', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725102/5_days_before_the_earnings.png', '5 days before the earnings'),
        (7, 'For you', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725085/Post_IPO.png', 'Post IPO'),
        (8, 'Recommended', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725106/Biotechnology.png', 'Biotechnology'),
        (9, 'Recommended', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725097/Future_of_transport.png', 'Future of transport'),
        (10, 'Recommended', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725099/Sharing_economy.png', 'Sharing economy'),
        (11, 'Recommended', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725102/High_growing_SP500_stocks.png', 'High growing SP500 stocks'),
        (12, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725102/Cloud_cloud_and_cloud.png', 'Cloud, cloud and cloud'),
        (13, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725082/Blockchain.png', 'Blockchain'),
        (14, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725075/VR_and_AR.png', 'VR and AR'),
        (15, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725086/AI.png', 'AI'),
        (16, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725094/Robotics.png', 'Robotics'),
        (17, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725104/Internet_of_things.png', 'Internet of things'),
        (18, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725077/Chip_makers_and_semiconductors.png', 'Chip makers and semiconductors'),
        (19, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725069/Cheap_and_growing_technology_companies.png', 'Cheap and growing technology companies'),
        (20, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725110/Technology_most_owned_by_institutions.png', 'Technology most owned by institutions'),
        (21, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725098/Online_education.png', 'Online education'),
        (22, 'Healthcare', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725074/Drug_manufacturing.png', 'Drug manufacturing'),
        (23, 'Healthcare', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725096/Telehealth_and_telemedicine.png', 'Telehealth and telemedicine'),
        (24, 'Healthcare', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725077/Medical_devices_and_instruments.png', 'Medical devices and instruments'),
        (25, 'Healthcare', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725105/Cheap_and_growing_healthcare_companies.png', 'Cheap and growing healthcare companies'),
        (26, 'Healthcare', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725094/Most_growing_healthcare_companies.png', 'Most growing healthcare companies'),
        (27, 'Healthcare', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725106/Healthcare_most_owned_by_institutions.png', 'Healthcare most owned by institutions'),
        (28, 'Healthcare', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725101/Most_recommended_healthcare_stocks.png', 'Most recommended healthcare stocks'),
        (29, 'Portfolios', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725071/George_Soros_portfolio.png', 'George Soros'' portfolio'),
        (30, 'Portfolios', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725084/Peter_Thiel_s_portfolio.png', 'Peter Thiel’s portfolio'),
        (31, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725085/Cybersecurity.png', 'Cybersecurity'),
        (32, 'Top', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725105/COVID-19_fighters.png', 'Fight with COVID-19'),
        (33, 'Healthcare', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064618/Genomics.png', 'Genomics'),
        (34, 'For you', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725077/Rule_of_40.png', 'Rule of forty'),
        (35, 'Recommended', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614188807/WFH_essentials.png', 'WFH essentials'),
        (36, 'Recommended', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064619/Foreign_most_growing_companies.png', 'Foreign most growing companies'),
        (37, 'Recommended', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064640/Technology.png', 'Most growing technology companies'),
        (38, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064633/Technology-1.png', 'Technology with high earnings grow'),
        (39, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064643/Technology-3.png', 'Technology most recommended by analysts'),
        (40, 'Healthcare', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064629/Stay_healthy.png', 'Stay healthy'),
        (41, 'Healthcare', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064612/Diagnosis_and_research.png', 'Diagnosis and research'),
        (42, 'Healthcare', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064622/Healthcare-1.png', 'Biggest healthcare companies'),
        (43, 'Healthcare', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064627/Healthcare-2.png', 'Healthcare with dividends'),
        (44, 'Healthcare', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064634/Healthcare.png', 'Healthcare with high earnings growth'),
        (45, 'Portfolios', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064600/Buffets_portfolio.png', 'Buffet''s portfolio'),
        (46, 'Portfolios', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064600/Bill_Gates_bets.png', 'Bill Gates'' portfolio'),
        (47, 'For you', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064627/Most_bought_by_hedge_funds.png', 'Most held by hedge funds'),
        (48, 'For you', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614188449/Companies_that_blocked_Trump.png', 'Companies that blocked Trump'),
        (49, 'Portfolios', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725104/Bill_Ackman_s_portfolio.png', 'Bill Ackman''s portfolio'),
        (50, 'Portfolios', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725074/Michael_Burry_s_portfolio.png', 'Michael Burry''s portfolio'),
        (51, 'Communication services', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725105/Gaming.png', 'Gaming'),
        (52, 'Communication services', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725085/Telecommunication.png', 'Telecommunication'),
        (53, 'Communication services', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725098/Cheap_and_growing_communication_services.png', 'Cheap and growing communication services'),
        (54, 'Communication services', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725101/Biggest_communication_services.png', 'Biggest communication services'),
        (55, 'Communication services', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725107/Communication_services_with_high_dividends.png', 'Communication services with high dividends'),
        (56, 'Communication services', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725101/Most_recommended_communication_services.png', 'Most recommended communication services'),
        (57, 'Basic materials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725088/Gold_miners.png', 'Gold miners'),
        (58, 'Basic materials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725097/Cheap_and_growing_basic_materials.png', 'Cheap and growing basic materials'),
        (59, 'Basic materials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725079/Basic_materials_with_high_dividends.png', 'Basic materials with high dividends'),
        (60, 'Consumer cyclical', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725100/Transportation.png', 'Transportation'),
        (61, 'Consumer cyclical', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725074/Biggest_consumer_cyclical.png', 'Biggest consumer cyclical'),
        (62, 'Consumer cyclical', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725086/Consumer_cyclical_with_high_dividends.png', 'Consumer cyclical with high dividends'),
        (63, 'Consumer cyclical', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725076/Consumer_cyclical_most_owned_by_institutions.png', 'Consumer cyclical most owned by institutions'),
        (64, 'Energy', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725080/Renewable_energy.png', 'Renewable energy'),
        (65, 'Energy', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725072/Cheap_and_growing_energy_stocks.png', 'Cheap and growing energy stocks'),
        (66, 'Energy', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725071/Utilities.png', 'Utilities'),
        (67, 'Energy', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725109/Most_growing_energy_companies-.png', 'Most growing energy companies'),
        (68, 'Energy', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725109/Biggest_energy_companies.png', 'Biggest energy companies'),
        (69, 'Energy', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725111/Energy_companies_with_high_earnings_growth.png', 'Energy companies with high earnings growth'),
        (70, 'Energy', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725079/Energy_most_owned_by_institutions.png', 'Energy most owned by institutions'),
        (71, 'Energy', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725110/Most_recommended_energy_stocks.png', 'Most recommended energy stocks'),
        (72, 'Finance', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725096/Fintech.png', 'Fintech'),
        (73, 'Finance', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725088/Asset_management.png', 'Asset management'),
        (74, 'Finance', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725101/banks_and_capital.png', 'Banks and capital markets'),
        (75, 'Finance', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725074/Insurance.png', 'Insurance'),
        (76, 'Energy', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614188461/Oil_and_gas_with_dividends.png', 'Oil and gas with dividends'),
        (77, 'Consumer cyclical', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725100/Cheap_and_growing.png', 'Cheap and growing consumer cyclical'),
        (78, 'Basic materials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064617/basic_materials-1.png', 'Most growing basic materials'),
        (79, 'Communication services', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064605/Communication-1.png', 'Social medias'),
        (80, 'Communication services', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064609/Communication-3.png', 'Most growing communication services'),
        (81, 'Communication services', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064606/Communication-2.png', 'Communication services with high earnings grow'),
        (82, 'Communication services', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064613/Communication.png', 'Communication services most owned by institutions'),
        (83, 'Basic materials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064602/basic_materials-5.png', 'Biggest basic materials companies'),
        (84, 'Basic materials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064594/basic_materials-2.png', 'Basic materials most owned by institutions'),
        (85, 'Basic materials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064622/basic_materials-4.png', 'Most recommended basic materials'),
        (86, 'Basic materials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064596/basic_materials.png', 'Basic materials with high earnings grow'),
        (87, 'Consumer cyclical', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064644/Travel.png', 'Travelling'),
        (88, 'Consumer cyclical', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064635/Restaurants.png', 'Restaurants'),
        (89, 'Portfolios', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614188448/Charlie_munger_s_bets.png', 'Charlie Munger’s portfolio'),
        (90, 'Consumer cyclical', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614188806/Auto_manufactures.png', 'Auto manufactures'),
        (91, 'Consumer cyclical', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614188475/Consumer.png', 'Most growing consumer cyclical'),
        (92, 'Consumer cyclical', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614188462/Consumer_2.png', 'Most recommended consumer cyclical by analysts'),
        (93, 'Finance', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725098/Financial-5.png', 'Biggest financial companies'),
        (94, 'Finance', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725110/Financial_with_high_earnings_growth.png', 'Financial with high earnings growths'),
        (95, 'Management', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725100/Companies_with_LGBTQ_management.png', 'Companies with LGBTQ management'),
        (96, 'Management', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725101/Woman_led.png', 'Woman led'),
        (97, 'Consumer defensive', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725099/Discount_retailers.png', 'Discount retailers'),
        (98, 'Consumer defensive', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725100/Personal_products.png', 'Personal products'),
        (99, 'Consumer defensive', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725108/Most_growing_consumer_defensive_companies.png', 'Most growing consumer defensive companies'),
        (100, 'Consumer defensive', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725079/Consumer_defensive_with_dividends.png', 'Consumer defensive with dividends'),
        (101, 'Consumer defensive', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725086/Consumer_defensive_with_high_earnings_growth.png', 'Consumer defensive with high earnings growth'),
        (102, 'Consumer defensive', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725088/Consumer_defensive_most_owned_by_institutions.png', 'Consumer defensive most owned by institutions'),
        (103, 'Consumer defensive', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725075/Most_recommended_consumer_defensive.png', 'Most recommended consumer defensive'),
        (104, 'Industrials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725109/Aerospace_and_defense.png', 'Aerospace and defense'),
        (105, 'Industrials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725084/Manufacturing.png', 'Manufacturing'),
        (106, 'Industrials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725080/Cheap_and_growing_industrials.png', 'Cheap and growing industrials'),
        (107, 'Industrials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725073/Most_growing_industrial_stocks.png', 'Most growing industrial stocks'),
        (108, 'Industrials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725104/Biggest_industrial_stocks.png', 'Biggest industrial stocks'),
        (109, 'Industrials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725069/Industrials_with_dividends.png', 'Industrials with dividends'),
        (110, 'Industrials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725075/Industrials_with_high_earnings_growth.png', 'Industrials with high earnings growth'),
        (111, 'Industrials', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725107/Industrial_most_owned_by_institutions.png', 'Industrial most owned by institutions'),
        (112, 'Real estate', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725100/Residential_real_estate.png', 'Residential real estate'),
        (113, 'Real estate', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725109/Biggest_real_estate_companies.png', 'Biggest real estate companies'),
        (114, 'Others', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725106/Cheap_SP500_stocks.png', 'Cheap SP500 stocks'),
        (115, 'Others', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725102/High_growing_SP500_stocks.png', 'High growing SP500 stocks'),
        (116, 'Others', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725098/Dowjones_stocks.png', 'Dowjones stocks'),
        (117, 'Others', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725108/Dividends_with_future.png', 'Dividends with future'),
        (118, 'For you', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1613904948/Food_delivery.png', 'Food delivery'),
        (119, 'Consumer cyclical', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1613904948/Airlines.png', 'Airlines'),
        (120, 'Finance', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725086/Financial_with_dividends.png', 'Financial companies with dividends'),
        (121, 'Management', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064601/Best_corporate_culture.png', 'Best corporate culture'),
        (122, 'Management', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725079/Companies_with_black_managers.png', 'Companies with black management'),
        (123, 'Management', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725071/With_strongest_management.png', 'With strongest management team'),
        (124, 'Real estate', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725073/Cheap_and_growing_real_estate_stocks.png', 'Cheap and growing real estate companies'),
        (125, 'Real estate', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725076/Most_growing_real_estate.png', 'Most growing real estate companies'),
        (126, 'Others', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614188807/Environment_friendly.png', 'Environment friendly'),
        (127, 'Real estate', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725094/Real_estate_with_high_earnings_growth.png', 'Real estate companies with high earnings growth'),
        (128, 'Real estate', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725074/Real_estate_most_owned_by_institutions.png', 'Real estate companies most owned by institutions'),
        (129, 'Real estate', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725094/Most_recommended_real_estate_stocks.png', 'Most recommended real estate companies'),
        (131, 'Recommended', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064644/Vaccine_producers.png', 'Vaccine producers'),
        (132, 'Consumer defensive', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725072/Cheap_and_growing_consumer_defensive.png', 'Cheap and growing consumer defensive'),
        (133, 'Finance', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064620/Financial.png', 'Most growing financial companies'),
        (134, 'Finance', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064615/Financial-1.png', 'Financial companies most owned by intuitions'),
        (135, 'Others', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064598/5_days_after_the_earnings.png', '5 days after the earnings'),
        (136, 'Consumer cyclical', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064641/Logistics.png', 'Logistics'),
        (137, 'Real estate', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064614/Estate.png', 'Real estate companies with high dividends'),
        (138, 'Top', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725102/Most_popular_stocks.png', 'Most popular stocks'),
        (139, 'Portfolios', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725108/Jim_Simmons_s_portfolio.png', 'Jim Simmons’ portfolio'),
        (140, 'Finance', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725069/Cheap_and_growing_financial_stocks.png', 'Cheap and growing financial companies'),
        (141, 'Finance', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725110/Most_recommended_financial_stocks.png', 'Most recommended financial companies'),
        (142, 'Consumer cyclical', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725094/Consumer_cyclical_with_high_earnings_grow.png', 'Internet retail'),
        (143, 'Others', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614064636/Super_bowl_commercials.png', 'Super bowl commercials'),
        (144, 'Technology', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1614188448/5g.png', '5G'),
        (130, 'Top', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1613904949/Elon_s_twitter.png', 'Elon''s twitter'),
        (4, 'For you', 'https://res.cloudinary.com/djqpn16qv/image/upload/v1612725077/Masayoshi_Son_s_portfolio.png', 'Masayoshi Son''s portfolio');