create table comment
(
	id bigint generated by default as identity
		constraint comment_pkey
			primary key,
	content varchar(200),
	published_at timestamp,
	author_user_id bigint
		constraint fki4xwyjsmhu648k3thg01nsqyw
			references users
);

alter table comment owner to hfpmlazvgosijf;

