create table payments
(
	id bigint generated by default as identity
		constraint payments_pkey
			primary key,
	amount numeric(19,2),
	day_created timestamp not null,
	from_user_id bigint
		constraint fk74waay8m8qk4vdxse9h88gg2w
			references users,
	to_user_id bigint
		constraint fk5ygpkypx3434pgm7c2dlclfxw
			references users
);

alter table payments owner to hfpmlazvgosijf;

