create table play_list
(
	id bigint generated by default as identity
		constraint play_list_pkey
			primary key,
	title varchar(255),
	description text
);

alter table play_list owner to hfpmlazvgosijf;

