create table play_list_wrapper
(
	id bigint generated by default as identity
		constraint play_list_wrapper_pkey
			primary key,
	category varchar(255)
);

alter table play_list_wrapper owner to hfpmlazvgosijf;

