create table play_listc
(
	id bigint generated by default as identity
		constraint play_listc_pkey
			primary key,
	category varchar(255),
	imageurl varchar(255),
	title varchar(255)
);

alter table play_listc owner to hfpmlazvgosijf;

