create table portfolios
(
	id bigint generated by default as identity
		constraint portfolios_pkey
			primary key,
	currency varchar(255),
	total_balance_now numeric(19,2),
	total_balance_prev_day numeric(19,2),
	trade_history varchar(255)
);

alter table portfolios owner to hfpmlazvgosijf;

