create table stock_play_list
(
	id bigint generated by default as identity
		constraint stock_play_list_pkey
			primary key,
	ticker varchar(200),
	company varchar(200),
	sector varchar(200),
	industry varchar(200),
	market_cap varchar(200),
	recom varchar(200)
);

alter table stock_play_list owner to hfpmlazvgosijf;

