create table stocks
(
	id bigint generated by default as identity
		constraint stocks_pkey
			primary key,
	bought_date timestamp,
	country varchar(255),
	currency varchar(255),
	description varchar(255),
	industry varchar(255),
	logo varchar(255),
	name varchar(255),
	phone varchar(255),
	share_outstanding double precision not null,
	ticker varchar(255),
	url varchar(255)
);

alter table stocks owner to hfpmlazvgosijf;

