create table trading
(
	id bigint generated by default as identity
		constraint trading_pkey
			primary key,
	priority_post double precision,
	news_id bigint
		constraint fkqq7k3drxhtg9j5a6psqow60b6
			references news,
	tweet_id bigint
		constraint fkp031pr4f52abs86ehnuiukho0
			references tweet
);

alter table trading owner to hfpmlazvgosijf;

