create table users
(
	user_id bigint generated by default as identity
		constraint users_pkey
			primary key,
	day_created timestamp,
	email varchar(255)
		constraint uk6dotkott2kjsp8vw4d0m25fb7
			unique,
	enable boolean not null,
	password varchar(255),
	phone varchar(255),
	username varchar(255)
		constraint ukr43af9ap4edm43mmtq01oddj6
			unique,
	portfolio_id bigint
		constraint fkonfi0p6h3fkvfq79otx2p5cc9
			references portfolios,
	profile_id bigint
		constraint fkq2e6rj0p6p1gec2cslmaxugw1
			references profiles,
	wallet_id bigint
		constraint fkcf6cgic6n7ek155uj81npsbcm
			references wallets,
	first_name varchar(255),
	last_name varchar(255),
	activated boolean default false,
	activated_code varchar(255)
);

alter table users owner to hfpmlazvgosijf;

