create table watchlist_item_description
(
	id bigint generated by default as identity
		constraint watchlist_item_description_pkey
			primary key,
	description text,
	ticker_name varchar(255)
);

alter table watchlist_item_description owner to hfpmlazvgosijf;

