create table watchlist_item_order
(
	id bigint generated by default as identity
		constraint watchlist_item_order_pkey
			primary key,
	user_user_id bigint
		constraint fktr0d4o214cn3l8wdau6gng7yy
			references users
);

alter table watchlist_item_order owner to hfpmlazvgosijf;

